### ISSUE TITLE
Borken "ESPectro32" symbolic link

### ISSUE THREAD

**Issue by ivankravets** [dycodex/ESPectro32#1]
Could you remove this file in the root fo repo? It breaks our PIO Library Registry Crawler.

Thanks!

**Comment by alwint3r** [comment]
Removed in 13caf9a. We never thought that would cause such thing.

**Comment by ivankravets** [comment]
Thanks! We should fix that on our side but I don't have time now :) The easiest way is to ask you remove it because it's broken in any case 😊
